# Generated by Django 5.1.3 on 2025-02-01 06:30

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Answer')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('or', 'Odia'), ('as', 'Assamese'), ('kok', 'Konkani'), ('mai', 'Maithili'), ('ne', 'Nepali'), ('sa', 'Sanskrit'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ru', 'Russian'), ('ar', 'Arabic'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('nl', 'Dutch')], default='en', max_length=5)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('or', 'Odia'), ('as', 'Assamese'), ('kok', 'Konkani'), ('mai', 'Maithili'), ('ne', 'Nepali'), ('sa', 'Sanskrit'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ru', 'Russian'), ('ar', 'Arabic'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ko', 'Korean'), ('tr', 'Turkish'), ('nl', 'Dutch')], max_length=5)),
                ('translated_question', models.TextField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='faqs.faq')),
            ],
            options={
                'unique_together': {('faq', 'language')},
            },
        ),
    ]
